--!strict
return {
	observeAttribute = require(script._observeAttribute),
	observeAllAttributes = require(script._observeAllAttributes),
	observeCharacter = require(script._observeCharacter),
	observeClass = require(script._observeClass),
	observeLocalCharacter = require(script._observeLocalCharacter),
	observePlayer = require(script._observePlayer),
	observeProperty = require(script._observeProperty),
	observeTag = require(script._observeTag),
	observeChildren = require(script._observeChildren),
	observeDescendants = require(script._observeDescendants),
	observeAncestry = require(script._observeAncestry)
}